### ISSUE TITLE
directional_derivative

### ISSUE THREAD

**Issue by hellomynameisjiji** [cfinlay/ffjord-rnode#2]
Hi! Thanks for your effort to release this repository.

I wonder what does the regularizer directional_derivative work for.
Also, my team and I have been working on training GAN with neural ODE while regularizing it by RNODE, but it's not easy to stably train the model. Could you give us any further suggestion or tips for stable training? 

Thanks! 

Sincerely,
Jiji

**Comment by cfinlay** [comment]
Hi Jiji

The directional derivative penalizes the Jacobian in the direction of the ODE's vector field. So if the ODE is dx/dt = v, and we let J be the Jacobian (J = dv/dx), then the directional derivative penalty is
|| J v || ^2

I hope that explains it sufficiently.

Regarding GAN stabilization... personally I have never had much success stabilizing GANS. Good luck! I would first try something like the Jacobian regularizer in RNODE

E_v [ ||J v || ^2 ]

where v is sampled randomly from the unit sphere.

Spectral normalization on the weight matrices might also help. You could also try encouraging the weight matrices to be orthogonal with a penalty

||I - W^t W||^2

Those are the first to come to mind... Best of luck!

-Chris
